package com.example.resume_chatbot.model;

public enum UserState {
    IDLE,
    AWAITING_RESUME_FOR_ANALYSIS,
    AWAITING_JOB_DESCRIPTION,
    AWAITING_RESUMES_FOR_COMPARE,
    AWAITING_JOB_DESCRIPTION_FOR_COMPARE,
    AWAITING_QUESTION,
    AWAITING_SKILL_FOR_COURSES
}
